<?php

namespace App\Support;

use GlimpseImg\ApiException;
use stdClass;

/**
 * A .glimpse-baseline.json file: a JSON list of already-processed files in
 * the directory glimpse is run from, so analyze and check skip them.
 * Entries match on relative path plus size plus xxh128 content hash; a
 * file whose content changed re-enters the scan. The hash is for change
 * detection, not security, so a fast non-cryptographic digest is the
 * right tool. Each entry also records which operation wrote it (via), so
 * a reader can tell a file that was merely accepted as-is (analyze) from
 * one glimpse actually worked on (convert, resize, thumbnail) or ran the
 * optimizer chain on (optimize, which any transform's --optimize flag
 * also reports).
 *
 * Concurrency: a run that will write loads with $forUpdate, which takes a
 * non-blocking exclusive lock on the file up front and holds it through
 * save(). Creating the file is exclusive too, so two first-time
 * generators cannot silently overwrite each other; the loser of any race
 * fails fast with a clear error. Writes land in a private temporary file
 * swapped into place with an atomic rename, so plain (unlocked) reads
 * never observe a half-written baseline and a failed or short write
 * leaves the previous file untouched.
 */
final class BaselineFile
{
    public const FILENAME = '.glimpse-baseline.json';

    /**
     * Self-documentation written to the top of the file on every save,
     * composer.lock style, so anyone reading the committed file knows
     * what it is without leaving it. Ignored (and regenerated) on load,
     * which is also why hand-added comments cannot survive: the file is
     * machine-rewritten.
     */
    public const README = [
        'Images already handled by glimpse: check and analyze skip a file while its size and xxh128 content hash still match its entry.',
        'via records the operation that wrote the entry: analyze means accepted as-is by --update-baseline, optimize means the optimizer chain ran (the optimize command or any transform\'s --optimize flag), and other values name the command that produced the file.',
        'This file is @generated by glimpse and rewritten on every update; do not edit by hand. See https://github.com/mathiasgrimm/glimpse-cli#glimpse-baselinejson',
    ];

    /**
     * @param  array<string, array{size: int, xxh128: string, via: string}>  $files
     * @param  resource|null  $handle  Locked handle held from load until save when loaded for update.
     */
    private function __construct(private array $files, private $handle = null) {}

    /**
     * Load the baseline at the directory. A missing or empty file is an
     * empty baseline; an unreadable or malformed one fails loudly so a
     * permission problem or a typo never turns into a silently
     * un-baselined (or fully skipped) scan. Pass $forUpdate when the
     * baseline will be saved: the first thing it does is try to lock the
     * file, failing fast when another process already holds it.
     */
    public static function load(string $directory, bool $forUpdate = false): self
    {
        $path = rtrim($directory, '/').'/'.self::FILENAME;

        if (! is_file($path)) {
            return new self([]);
        }

        if (! $forUpdate) {
            $content = @file_get_contents($path);

            if ($content === false) {
                throw new ApiException("Could not read {$path}.");
            }

            $content = trim($content);

            return new self($content === '' ? [] : self::parse($content, $path));
        }

        $handle = @fopen($path, 'r+');

        if ($handle === false) {
            throw new ApiException("Could not read {$path}.");
        }

        if (! flock($handle, LOCK_EX | LOCK_NB)) {
            fclose($handle);

            throw new ApiException("{$path} is locked by another glimpse process.");
        }

        try {
            // Saves swap the path to a new inode; if that happened between
            // our open and the flock, this lock is on the orphaned old
            // file and another writer could hold the real one.
            clearstatcache(true, $path);
            $onDisk = @stat($path);
            $held = fstat($handle);

            if ($onDisk === false || $held === false || $onDisk['ino'] !== $held['ino']) {
                throw new ApiException("{$path} is locked by another glimpse process.");
            }

            $content = trim((string) stream_get_contents($handle));
            $files = $content === '' ? [] : self::parse($content, $path);
        } catch (ApiException $exception) {
            flock($handle, LOCK_UN);
            fclose($handle);

            throw $exception;
        }

        return new self($files, $handle);
    }

    /**
     * Decode and validate baseline JSON into the entry map.
     *
     * @return array<string, array{size: int, xxh128: string, via: string}>
     */
    private static function parse(string $content, string $path): array
    {
        $decoded = json_decode($content, true);

        if (! is_array($decoded) || ! is_array($decoded['files'] ?? null)) {
            throw new ApiException("Malformed {$path}: expected a JSON object with a \"files\" object.");
        }

        $files = [];

        foreach ($decoded['files'] as $relative => $entry) {
            if (! is_string($relative) || ! is_array($entry) || ! is_int($entry['size'] ?? null) || ! is_string($entry['xxh128'] ?? null) || ! is_string($entry['via'] ?? null)) {
                throw new ApiException("Malformed {$path}: every entry needs an integer \"size\", a string \"xxh128\", and a string \"via\".");
            }

            $files[$relative] = ['size' => $entry['size'], 'xxh128' => $entry['xxh128'], 'via' => $entry['via']];
        }

        return $files;
    }

    /**
     * Whether the file is covered by the baseline: known path, same size,
     * same content. Size is compared first so the hash is only computed
     * when it could possibly match.
     */
    public function skips(string $relative, string $absolute): bool
    {
        $entry = $this->files[$relative] ?? null;

        if ($entry === null) {
            return false;
        }

        if (@filesize($absolute) !== $entry['size']) {
            return false;
        }

        return @hash_file('xxh128', $absolute) === $entry['xxh128'];
    }

    /**
     * Add or refresh the entry for the file from its current on-disk
     * content. A file that vanished or turned unreadable in the meantime
     * is skipped rather than crashing the run; it either no longer needs
     * an entry or will simply re-enter the next scan.
     */
    public function record(string $relative, string $absolute, string $via): void
    {
        $size = @filesize($absolute);
        $hash = $size === false ? false : @hash_file('xxh128', $absolute);

        if ($size === false || $hash === false) {
            return;
        }

        $this->put($relative, $size, $hash, $via);
    }

    /**
     * Add or refresh an entry from a size and hash that were already
     * computed, e.g. from bytes the caller had in memory. The via is the
     * name of the command writing the entry.
     */
    public function put(string $relative, int $size, string $hash, string $via): void
    {
        $this->files[$relative] = ['size' => $size, 'xxh128' => $hash, 'via' => $via];
    }

    public function forget(string $relative): void
    {
        unset($this->files[$relative]);
    }

    /**
     * Drop entries whose file no longer exists under the directory.
     */
    public function prune(string $directory): void
    {
        $root = rtrim($directory, '/');

        foreach (array_keys($this->files) as $relative) {
            if (! is_file($root.'/'.$relative)) {
                unset($this->files[$relative]);
            }
        }
    }

    public function count(): int
    {
        return count($this->files);
    }

    /**
     * Write the baseline out under the lock taken at load time, or, when
     * the file did not exist yet, by creating it exclusively now, so two
     * first-time generators cannot silently overwrite each other. The
     * content lands in a temporary file swapped into place atomically.
     * Fails loudly instead of quietly losing entries: an unencodable
     * filename (caught before any file is touched), a lost creation race,
     * a held lock, or a failed or short write must never quietly replace
     * a healthy committed baseline with garbage. Whatever happens, a lock
     * taken at load time is released here and a failed creation leaves no
     * file behind.
     */
    public function save(string $directory): void
    {
        ksort($this->files);

        $path = rtrim($directory, '/').'/'.self::FILENAME;
        $handle = $this->handle;
        $created = false;

        try {
            $json = json_encode([
                '_readme' => self::README,
                'files' => $this->files === [] ? new stdClass : $this->files,
            ], JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES);

            if ($json === false) {
                throw new ApiException("Could not encode {$path}: ".json_last_error_msg().'. Is a filename not valid UTF-8?');
            }

            if ($handle === null) {
                $opened = @fopen($path, 'x+');

                if ($opened === false) {
                    throw new ApiException(is_file($path)
                        ? "{$path} was created by another glimpse process since this run started; re-run to update it."
                        : "Could not write {$path}.");
                }

                $handle = $opened;
                $created = true;

                if (! flock($handle, LOCK_EX | LOCK_NB)) {
                    throw new ApiException("{$path} is locked by another glimpse process.");
                }
            }

            self::writeAtomically($path, $json.PHP_EOL);
        } catch (ApiException $exception) {
            if ($created) {
                @unlink($path);
            }

            throw $exception;
        } finally {
            if ($handle !== null) {
                flock($handle, LOCK_UN);
                fclose($handle);
            }

            $this->handle = null;
        }
    }

    /**
     * Write the content to a private temporary file next to the target
     * and swap it into place with an atomic rename, so a reader never
     * observes a half-written baseline and a failed or short write leaves
     * the previous file untouched. The caller holds the lock that
     * serializes writers.
     */
    private static function writeAtomically(string $path, string $data): void
    {
        $tmp = $path.'.'.getmypid().'.tmp';

        try {
            if (@file_put_contents($tmp, $data) !== strlen($data)) {
                throw new ApiException("Could not write {$path}.");
            }

            if (! @rename($tmp, $path)) {
                throw new ApiException("Could not write {$path}.");
            }
        } finally {
            if (is_file($tmp)) {
                @unlink($tmp);
            }
        }
    }
}
