name: Images

on:
  push:
    branches: [main]
  pull_request:

jobs:
  images:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          coverage: none

      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction --no-progress

      - name: Check images
        run: ./glimpse check .
        env:
          GLIMPSE_TOKEN: ${{ secrets.GLIMPSE_TOKEN }}
